filebeat.inputs:
- type: log
  enabled: true
  paths:
    - /var/lib/asterisk/agi-bin/log/*.log

filebeat.config.modules:
  path: ${path.config}/modules.d/*.yml
  reload.enabled: false

setup.template.settings:
  index.number_of_shards: 3


output.elasticsearch:
  hosts: ["http://35.232.243.122:9200"]
